// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNoWGo1SXOD0Kfd4SOZ8PgHwYqILbQbUI',
    appId: '1:830369899680:web:e5a466f3e6f7bd70e895c5',
    messagingSenderId: '830369899680',
    projectId: 'mypetinfo-day',
    authDomain: 'mypetinfo-day.firebaseapp.com',
    storageBucket: 'mypetinfo-day.appspot.com',
    measurementId: 'G-VS5Q42HME9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjG1qQ8L_pLDWa1P_wdJz63XjJebmdP1E',
    appId: '1:830369899680:android:3bf1fb905cb6e33ce895c5',
    messagingSenderId: '830369899680',
    projectId: 'mypetinfo-day',
    storageBucket: 'mypetinfo-day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqE6RlJAqiwEi0SnwlVBWMV3pUZyY1E0E',
    appId: '1:830369899680:ios:94933ac2ea880afee895c5',
    messagingSenderId: '830369899680',
    projectId: 'mypetinfo-day',
    storageBucket: 'mypetinfo-day.appspot.com',
    iosBundleId: 'com.example.myPetInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqE6RlJAqiwEi0SnwlVBWMV3pUZyY1E0E',
    appId: '1:830369899680:ios:83dbfe10c35eb64ce895c5',
    messagingSenderId: '830369899680',
    projectId: 'mypetinfo-day',
    storageBucket: 'mypetinfo-day.appspot.com',
    iosBundleId: 'com.example.myPetInfo.RunnerTests',
  );
}
